const swaggerAutogen = require('swagger-autogen')()
const dotenv = require('dotenv');
dotenv.config();
const outputFile = './swagger_output.json'
const endpointsFiles = ["./routes/ChapterRoutes.js","./routes/ChapterInfoRoutes.js","./routes/ChapterMemberRoutes.js","./routes/EventRoutes.js","./routes/EventTypeRoutes.js","./routes/GalleryRoutes.js","./routes/MemberRoutes.js","./routes/RoleRoutes.js"]

const port = process.env.HOST_FOR_SWAGGER || 'localhost:4000'

const doc = {
    info: {
        version: "1.0.0",
        title: "This project is the rest API of the student branch of University El Bosque.",
        description: "Documentation automatically generated by the <b>swagger.autogen</b> module."
    },
    host: port,
    basePath: "/api",
    schemes: ['http','https'],
    consumes: ['application/json','multipart/form-data'],
    produces: ['application/json'],
    definitions: {
        Chapter:{
            "name":"",
            "description":"",
            "logo_path":"",
            "start_date":"",
            "end_date":"",
            "isActive":""
        },
        ChapterInfo:{
            "mission":"",
            "vission":"",
            "objectives":"",
            "chapter_id":"",
        },
        ChapterMember:{
            "isActive":"",
            "start_date":"",
            "end_date":""
        },
        
        Event:{
           "title":"",
           "description":"",
           "start_date":"",
           "end_date":"",
           "event_type_id":"",
           "chapter_id":"",
        },
        EventType:{
            "event_type":""
        },
        Gallery:{
            "name":"",
            "path":"",
            "description":"",
            "event_id":"",

        },
        Member:{
            "firstname":"",
            "lastname":"",
            "email":"email@email.com",
            "password":"",
            "document":"",
            "phone":"",
            "image_path":""
        },
        Role:{
            "name":"",
            "description":"",
            "canCreate":"",
            "canDelete":"",
            "canUpdate":"",
        }     
       
    }
}

swaggerAutogen(outputFile, endpointsFiles,doc).then(() => {
    require('./index.js')
})
