const swaggerAutogen = require('swagger-autogen')()
const dotenv = require('dotenv')
dotenv.config();
const outputFile = './swagger_output.json'
const endpointsFiles = ["./routes/MemberRoutes.js"]

const port = process.env.HOST_FOR_SWAGGER || 'localhost:4000'

const doc = {
    info: {
        version: "1.0.0",
        title: "This project is the rest API of the student branch of University El Bosque.",
        description: "Documentation automatically generated by the <b>swagger.autogen</b> module."
    },
    host: port,
    basePath: "/api",
    schemes: ['http','https'],
    consumes: ['application/json','multipart/form-data'],
    produces: ['application/json'],
    definitions: {
        Member:{
            "firstname":"",
            "lastname":"",
            "email":"email@email.com",
            "password":"",
            "document":"",
            "phone":""
        }
    }
}

swaggerAutogen(outputFile, endpointsFiles,doc).then(() => {
    require('./index.js')
})
